---
- name: Install and setup mongodb
  hosts: all
  become: yes

  roles:
    - name: mongodb-install-role

- name: Setup and start mongodb config-cluster
  hosts: config_cluster
  become: yes
 
  roles:
   - name: mongodb-config-servers-role
