---
#copy mongodb.conf with authorization disabled
- name: Copy a new 'mongod.conf' file
  copy:
    src: ../files/mongodb-config-file
    dest: /etc/mongod.conf

- name: Start and enable mongod service
  service:
    name: mongod
    state: started
    enabled: true
