---
#Install mongodb

- name: Install MongoDb
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: Prevent MongoDb from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
      - mongodb-org
      - mongodb-org-database
      - mongodb-org-server
      - mongodb-mongosh
      - mongodb-org-mongos
      - mongodb-org-tools

- name: Verify if keys directory exist
  become: no
  stat:
    path: /var/lib/mongodb/keys
  register: keys_dir

- name: Create directory keys
  become: no
  shell: mkdir /var/lib/mongodb/keys
  when: not keys_dir.stat.exists

- name: Copy key file
  become: no
  copy:
    src: ~/mongodKey
    dest: /var/lib/mongodb/keys/mongodKey
    owner: "mongodb"
    group: "mongodb"
    mode: '0400'
